#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  -ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1

image: Visual Studio 2017