#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  -ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

image: Visual Studio 2017